# default database properties
database:
  host: localhost
  port: 3306
  username:
  password:

# spring datasource properties
spring:
  datasource:
    url: jdbc:mysql://${database.host}:${database.port}/javatask?createDatabaseIfNotExist=true
    username: ${database.username}
    password: ${database.password}
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2:
      time-between-eviction-runs-millis: 1

  # migrations
  liquibase:
    change-log: classpath:db-migrations/changelog.xml

#logging
logging:
  file: ./log/java-task-application.log
  level:
    ROOT: OFF
    ee.neotech.javatask: INFO